; PlatformIO Project Configuration File for the Anjoman Swarm Robot Project
; ESP32-S3 Single-MCU Hardware Architecture (WROOM-1-N8R2)

[env]
platform = espressif32 @ ^6.6.0
framework = arduino
monitor_speed = 115200
board = esp32-s3-devkitc-1

; Hardware Specification and Memory Map
board_build.arduino.memory_type = qio_qspi ; Quad SPI Flash + Quad SPI PSRAM
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv

; Build Preprocessor Flags
build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3 ; 3: Info level messages, ideal for runtime logging

; Automated External Library Dependancy Management
lib_deps = 
    https://github.com/stm32duino/VL53L7CX
    https://github.com/F-Army/arduino-dw1000-ng.git#master

; -----------------------------------------------------------------------------
; USB-UART Direct Flashing Environment
; -----------------------------------------------------------------------------
[env:esp32_usb]
upload_protocol = esptool

; -----------------------------------------------------------------------------
; Wireless Over-The-Air (OTA) Swarm Flashing Environment
; -----------------------------------------------------------------------------
[env:esp32_ota]
upload_protocol = espota
upload_port = 192.168.1.150 ; Targeted static IP of the active robot node
